

# This file was *autogenerated* from the file exercises.sage
from sage.all_cmdline import *   # import sage library

_sage_const_45 = Integer(45); _sage_const_10 = Integer(10); _sage_const_13 = Integer(13); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12)#x = var('x')
#print(solve(x^2 + 3*x + 2, x))

# 5:
#print(ZZ(27).quo_rem(ZZ(5)))
#print(ZZ(27).quo_rem(ZZ(-5)))
##print(ZZ(127).quo_rem(ZZ(0)))
#print(ZZ(-1687).quo_rem(ZZ(11)))
#print(ZZ(0).quo_rem(ZZ(7)))

# 8:
print(ZZ(_sage_const_45 ).xgcd(ZZ(_sage_const_10 ))) # 5 = 1 * 45 + -4 * 10
print(ZZ(_sage_const_13 ).xgcd(ZZ(_sage_const_11 )))
print(ZZ(_sage_const_13 ).xgcd(ZZ(_sage_const_12 )))

