

# This file was *autogenerated* from the file exercises.sage
from sage.all_cmdline import *   # import sage library

_sage_const_27 = Integer(27); _sage_const_5 = Integer(5); _sage_const_1687 = Integer(1687); _sage_const_11 = Integer(11); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7)#x = var('x')
#print(solve(x^2 + 3*x + 2, x))

# 5:
print(ZZ(_sage_const_27 ).quo_rem(ZZ(_sage_const_5 )))
print(ZZ(_sage_const_27 ).quo_rem(ZZ(-_sage_const_5 )))
#print(ZZ(127).quo_rem(ZZ(0)))
print(ZZ(-_sage_const_1687 ).quo_rem(ZZ(_sage_const_11 )))
print(ZZ(_sage_const_0 ).quo_rem(ZZ(_sage_const_7 )))

